name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - 'kind/api-change-breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/dependency'
      - 'kind/cleanup'
      - 'kind/documentation'
      - 'kind/maintainer-experience'
      - 'kind/consumer-experience'
      - 'kind/contributor-experience'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
